// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6da_Dy4vIH7G51htrxXS2BJBljUqL3Wk',
    appId: '1:55869154761:web:2fc40527b3fca218abf418',
    messagingSenderId: '55869154761',
    projectId: 'bandoso-2986b',
    authDomain: 'bandoso-2986b.firebaseapp.com',
    databaseURL: 'https://bandoso-2986b-default-rtdb.firebaseio.com',
    storageBucket: 'bandoso-2986b.appspot.com',
    measurementId: 'G-J33W9B3E0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLK_gdR8tgsqT27GDhqB4cM_rBQ5WeRU',
    appId: '1:55869154761:android:af4ecf9f6b9ab777abf418',
    messagingSenderId: '55869154761',
    projectId: 'bandoso-2986b',
    databaseURL: 'https://bandoso-2986b-default-rtdb.firebaseio.com',
    storageBucket: 'bandoso-2986b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0rnDiav5xlhlMf62jyFGwQxmVkKpIIQ',
    appId: '1:55869154761:ios:42256edd97a4fd2cabf418',
    messagingSenderId: '55869154761',
    projectId: 'bandoso-2986b',
    databaseURL: 'https://bandoso-2986b-default-rtdb.firebaseio.com',
    storageBucket: 'bandoso-2986b.appspot.com',
    iosBundleId: 'com.example.bandoso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq0rnDiav5xlhlMf62jyFGwQxmVkKpIIQ',
    appId: '1:55869154761:ios:42256edd97a4fd2cabf418',
    messagingSenderId: '55869154761',
    projectId: 'bandoso-2986b',
    databaseURL: 'https://bandoso-2986b-default-rtdb.firebaseio.com',
    storageBucket: 'bandoso-2986b.appspot.com',
    iosBundleId: 'com.example.bandoso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6da_Dy4vIH7G51htrxXS2BJBljUqL3Wk',
    appId: '1:55869154761:web:06df1142249f4eebabf418',
    messagingSenderId: '55869154761',
    projectId: 'bandoso-2986b',
    authDomain: 'bandoso-2986b.firebaseapp.com',
    databaseURL: 'https://bandoso-2986b-default-rtdb.firebaseio.com',
    storageBucket: 'bandoso-2986b.appspot.com',
    measurementId: 'G-LRBK5ZKV8L',
  );
}
